// <auto-generated />
namespace CoSys.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _343 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_343));
        
        string IMigrationMetadata.Id
        {
            get { return "201710200257068_343"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
